export enum ValidRoles {
    ADMIN = 'admin',
    SUPER_ADMIN = 'super-admin',
    USER = 'user',
    CONTROL_PANEL = 'panel-de-control',
    MY_BUSINESS = 'mi-negocio',
    SALES = 'ventas',
    INVENTORY = 'inventario',
    SHOPPING = 'compras',
    GENERAL_ACCOUNTING = 'contabilidad-general',
    HUMAN_RESOURCES = 'rrhh',
    ACCOUNTS_TO_PAY = 'cuentas-por-pagar',
    ACCOUNTS_TO_RECEIVE = 'cuentas-por-cobrar',
    ONLINE_SHOP = 'tienda-online',
}