export enum YesNo {
    YES = 'YES',
    NO = 'NO'
}

export enum TypeElement {
    input = 'input',
    inputCalendar = 'input-calendar',
    autoComplete = 'auto-complete',
    file = 'file',
    dropdown = 'dropdown',
    checkbox = 'checkbox',
    radio = 'radio',
    textarea = 'textarea',    
    inputVerify = 'input-verify',
    inputNumber = 'input-number',    
    inputMask = 'input-mask',
    fieldSet = 'field-set',
    toolbar = 'toolbar'
}

export enum StateToFilter {
    AccountCatalogue = 'accountCatalogue.AccountCatalogue',
    Brand = 'brand.Brands',
    Category = 'category.Categories',
    Enterprise = 'enterprise.Enterprises',
    InventoryTransaction =  'inventoryTransaction.InventoryTransaction',
    ProductType = 'productType.ProductTypes',
    Product = 'productos.Products',
    Provider = 'provider.Providers',
    Warehouse = 'wareHouse.WareHouses',
    Movement = 'movement.Movements',
    PaymentsCondition = 'paymentCondition.PaymentsCondition',
    User = 'user.Users',
    Currency = 'currency.Currencies',
    PurchaseOrder = 'purchaseOrder.PurchaseOrders',
}

export enum TypeColumn {
    Image = 'image',
    Price = 'price',
    Discount = 'discount',
    Text = 'text',
    Number = 'number',
    Actions = 'actions',
    Affirmation = 'affirmation',
    Input = 'input'
}

export enum UrlProgram {
    Dashboard ='dashboard',
    GestionDeUsuarios ='gestion-de-usuarios',
    GestionDeProcedimientos ='gestion-de-procedimientos',
    MiEmpresa ='mi-empresa',
    GestionDeMonedas ='gestion-de-monedas',
    GestionDeSucursales  ='gestion-de-sucursales',
    GestionDeProductos ='gestion-de-productos',
    GestionDeBodegas ='gestion-de-bodegas',
    GestionDeMarcas ='gestion-de-marcas',
    GestionDeCategorias ='gestion-de-categorias',
    GestionDeTipoProductos ='gestion-de-tipo-productos',
    GestionDeAtributos ='gestion-de-atributos',
    GestionTiposMovimientos ='gestion-tipos-movimientos',
    GestionTransaccionesInventario ='gestion-transacciones-inventario',
    ConteoProductos ='conteo-productos',
    GestionDeTransportistas ='gestion-de-transportistas',
    ReporteCatalogoProductos ='reporte-catalogo-productos',
    ReporteOperacionesPorMovimientos ='reporte-operaciones-por-movimientos',
    GestionExistenciasAlmacenes ='gestion-existencias-almacenes',
    PosSystem ='pos-system',
    GeneracionFormulario607 ='generacion_formulario_607',
    OfertasPromociones ='ofertas-promociones',
    GestionDeClientes ='gestion-de-clientes',
    GestionDeOrdenesDePedidos ='gestion-de-ordenes-de-pedidos',
    GestionDeCotizaciones ='gestion-de-cotizaciones',
    GestionDeCondicionesDePago ='gestion-de-condiones-de-pago',
    TablaAmortizaciones ='tabla-amortizaciones',
    GestionDeOrdenesCompras ='gestion-de-ordenes-compras',
    GestionDeProveedores ='gestion-de-proveedores',
    GestionDeRequisiciones ='gestion-de-requisiciones',
    GestionDireccionesEnvio ='gestion-direcciones-envio',
    CatalogoDeProveedores ='catalogo-de-proveedores',
    GestionCatalogoCuentas ='gestion-catalogo-cuentas',
    ReporteDiarioGeneral ='reporte-diario-general',
    GestionPeriodosFiscales ='gestion-periodos-fiscales',
    GestionEntradasDiario ='gestion-entradas-diario',
    GestionTransaccionesPago ='gestion-transacciones-pago',
    ReporteCatalogo ='reporte-catalogo',
    GastosDepartamento ='gastos-departamento',
    ReporteMayorGeneral ='reporte-mayor-general',
    CuadreCaja ='cuadre-caja',
    GestionEstados ='gestion-estados',
    GestionDeEmpleados ='gestion-de-empleados',
    GestionDePuestos ='gestion-de-puestos',
    GestionDeDepartamentos ='gestion-de-departamentos',
    GestionTipoTurnos ='gestion-tipo-turnos',
    GestionDeAreas ='gestion-de-areas',
    ReporteAnalisisSaldo ='reporte-analisis-saldo',
    GestionFacturaProveedores ='gestion-factura-proveedores',
    CreacionProductosPlaza ='creacion-productos-plaza',
}